In [4]:
import torch
import numpy as np
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [5]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [7]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.1792, -1.7461, -0.2906],
        [ 0.0863, -1.1291, -0.8181]], requires_grad=True)
tensor([ 0.6173, -0.7461], requires_grad=True)


In [8]:
def model(x):
    return x @w.t()+b

In [9]:
preds=model(inputs)
print(preds)

tensor([[-214.9489, -105.2758],
        [-278.9454, -144.6139],
        [-352.8072, -191.9900],
        [-205.4941,  -70.7664],
        [-268.7163, -160.4534]], grad_fn=<AddBackward0>)


In [10]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
diff=preds-targets
diff_sqr=diff*diff
torch.sum(diff*diff)/diff.numel()


tensor(90187.6797, grad_fn=<DivBackward0>)

In [14]:
#MSE loss
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [16]:
loss=mse(preds,targets)
print(loss)

tensor(90187.6797, grad_fn=<DivBackward0>)


In [17]:
loss.backward()

In [18]:
print(w)
print(w.grad)

tensor([[-1.1792, -1.7461, -0.2906],
        [ 0.0863, -1.1291, -0.8181]], requires_grad=True)
tensor([[-28486.8730, -31703.5938, -19297.9121],
        [-18738.9180, -21673.5293, -13130.9336]])


In [19]:
print(b)
print(b.grad)

tensor([ 0.6173, -0.7461], requires_grad=True)
tensor([-340.3824, -226.6199])


In [20]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [21]:
print(w)
print(b)

tensor([[-0.8943, -1.4291, -0.0976],
        [ 0.2737, -0.9124, -0.6868]], requires_grad=True)
tensor([ 0.6207, -0.7438], requires_grad=True)


In [22]:
#calculate loss
preds=model(inputs)
loss=mse(preds, targets)
loss.backward()
print(loss)

tensor(61210.9922, grad_fn=<DivBackward0>)


In [35]:
#Train for multiple epochs(runs)
for i in range(150):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [36]:
#calculate loss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(18.0044, grad_fn=<DivBackward0>)


In [37]:
import jovian
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Committed successfully! https://jovian.ai/v-jha85/pytorch-linear-regression


'https://jovian.ai/v-jha85/pytorch-linear-regression'

In [38]:
 import torch.nn as nn

In [39]:
print(w)
print(b)

tensor([[-0.4061,  0.7799,  0.7957],
        [-0.1335,  0.9685,  0.3870]], requires_grad=True)
tensor([ 0.6173, -0.7398], requires_grad=True)


In [108]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [109]:
from torch.utils.data import TensorDataset

In [110]:
train_ds=TensorDataset(inputs,targets)
train_ds[[1,3,5,7]]

(tensor([[ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 74.,  66.,  43.],
         [ 88., 134.,  59.]]),
 tensor([[ 81., 101.],
         [ 22.,  37.],
         [ 57.,  69.],
         [118., 132.]]))

In [111]:
from torch.utils.data import DataLoader

In [112]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [161]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    

tensor([[ 87., 135.,  57.],
        [102.,  43.,  37.],
        [ 91.,  87.,  65.],
        [ 68.,  97.,  70.],
        [101.,  44.,  37.]])
tensor([[118., 134.],
        [ 22.,  37.],
        [ 80., 102.],
        [102., 120.],
        [ 21.,  38.]])
tensor([[ 74.,  66.,  43.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 88., 134.,  59.],
        [ 73.,  66.,  44.]])
tensor([[ 57.,  69.],
        [103., 119.],
        [119., 133.],
        [118., 132.],
        [ 57.,  69.]])
tensor([[ 68.,  96.,  71.],
        [ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [ 92.,  87.,  64.],
        [103.,  43.,  36.]])
tensor([[104., 118.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 82., 100.],
        [ 20.,  38.]])


In [162]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2535, -0.5467, -0.5594],
        [-0.5011,  0.1743,  0.3789]], requires_grad=True)
Parameter containing:
tensor([-0.4603, -0.3651], requires_grad=True)


In [163]:
list (model.parameters())

[Parameter containing:
 tensor([[-0.2535, -0.5467, -0.5594],
         [-0.5011,  0.1743,  0.3789]], requires_grad=True),
 Parameter containing:
 tensor([-0.4603, -0.3651], requires_grad=True)]

In [164]:
preds=model(inputs)
preds

tensor([[ -79.6452,   -8.9689],
        [-107.4352,   -6.3699],
        [-128.2131,    1.3805],
        [ -70.5186,  -29.9570],
        [-109.5889,    8.3214],
        [ -79.3520,   -9.6443],
        [-107.4479,   -6.1653],
        [-129.0259,    1.2583],
        [ -70.8119,  -29.2816],
        [-109.8948,    9.2014],
        [ -79.6579,   -8.7643],
        [-107.1420,   -7.0453],
        [-128.2004,    1.1759],
        [ -70.2127,  -30.8369],
        [-109.8821,    8.9968]], grad_fn=<AddmmBackward0>)

In [165]:
#loss
import torch.nn.functional as F
loss_fn=F.mse_loss
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(22039.1621, grad_fn=<MseLossBackward0>)


In [166]:
#optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)


In [167]:
#utility function to train model
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            #print(model.weight,model.bias)
            pred=model(xb)
            loss=loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1) % 10==0:
            print('Epoch [{}/{}],Loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))
    

In [168]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100],Loss: 608.4096
Epoch [20/100],Loss: 208.3013
Epoch [30/100],Loss: 254.6902
Epoch [40/100],Loss: 120.4502
Epoch [50/100],Loss: 85.6475
Epoch [60/100],Loss: 82.6694
Epoch [70/100],Loss: 44.4844
Epoch [80/100],Loss: 42.9606
Epoch [90/100],Loss: 14.5884
Epoch [100/100],Loss: 26.0842


In [169]:
pred=model(inputs)
loss=loss_fn(pred,targets)
loss

tensor(23.1626, grad_fn=<MseLossBackward0>)

In [170]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "v-jha85/pytorch-linear-regression" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/v-jha85/pytorch-linear-regression


'https://jovian.ai/v-jha85/pytorch-linear-regression'